### ISSUE TITLE
Syntax error breaks test suite

### ISSUE THREAD

**Issue by szeidman** [learn-co-students/js-principles-scope-lab-v-000#2]
When "attemptTwoFavoriteCustomers()" declares two let or const variables in a row the syntax error causes all of the tests to fail. (For now I got the test to pass by manually throwing a syntax error from the attemptTwoFavoriteCustomers() function.)

**Comment by gb23** [comment]
See above.

**Comment by itzsaga** [comment]
I just ran into this with a student using the LearnIDE and Chrome v56.0.2924.87

**Comment by Joeycho** [comment]
Same as well!!

In the test of "attempTwoFavoriteCustomers()" function, there is an error not to throw syntax error.

**Comment by tracypholmes** [comment]
@gj also having this issue. Local Environment - Ubuntu 17.10.  Workaround provided by @szeidman is valid.

**Comment by gj** [comment]
cc: @JeffKatzy @curiositypaths

**Comment by marielfrank** [comment]
Having the same issue!

**Comment by curiositypaths** [comment]
Hi there,

Thank you for reporting the issue. attemptTwoFavoriteCustomers() does error on certain browsers. We removed the failing assignment.

As always, thanks for contributing! 💙
